FROM alpine
WORKDIR /app2
COPY entrypoint.sh entrypoint.sh
# COPY cmd.sh cmd.sh
RUN chmod +x *.sh

ENTRYPOINT ["sh","./entrypoint.sh"]
# CMD ["./cmd.sh"]
# CMD ["bash"]
# ENTRYPOINT ["/bin/echo", "Hello","ls"]





